# Generated by Django 5.0.2 on 2025-01-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory_management.units'),
            preserve_default=False,
        ),
    ]
